name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]


jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    runs-on: ubuntu-18.04
    container:
            image: ghcr.io/avcuenes/my_special_ubuntu:latest
            credentials:
               username: avcuenes
               password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
   

          
    steps:   
    - uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    
    
    - name: make 
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.bash
        colcon build
